# Generated by Django 4.0 on 2022-07-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Уникальное название курса')),
                ('title', models.CharField(max_length=120, verbose_name='Название курса')),
                ('desc', models.TextField(verbose_name='Описаниe')),
                ('img', models.ImageField(default='default.png', upload_to='course_images', verbose_name='Изображение')),
            ],
        ),
    ]
