# Generated by Django 4.0 on 2022-07-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Уникальное название курса')),
                ('title', models.CharField(max_length=120, verbose_name='Название курса')),
                ('desc', models.TextField(verbose_name='Описаниe')),
                ('number', models.IntegerField(verbose_name='Number of course')),
                ('video', models.CharField(max_length=100, verbose_name='Video URL')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Which course?')),
            ],
        ),
    ]
